name: Generate Hugo site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Build Site
      uses: chabad360/hugo-actions@master
      with:
        args: "--destination web"
    - name: debug
      run: ls -la
    - name: debug2
      run: ls -la web
    - name: Deploy site
      uses: appleboy/scp-action@master
      with:
        rm: true
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.KEY }}
        source: "web"
        target: ${{ secrets.TARGET }}
