name: Generate Hugo site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
    - name: configure
      run: ./configure
    - name: Build Site
      uses: chabad360/hugo-actions@master
