name: Generate Hugo site

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Update submodules
      uses: srt32/git-actions
      with:
        args: "git submodule update --init --recursive" 
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
    - name: Build site
      run: hugo --minify --destination web
    - name: debug
      run: ls -la
    - name: debug2
      run: ls -la web
    - name: Deploy site
      uses: appleboy/scp-action@master
      with:
        rm: true
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.KEY }}
        source: "web"
        target: ${{ secrets.TARGET }}
